# docker-compose.yml (简化后)
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: geo_history_studio_app
    env_file:
      - .env
    ports:
      - '8765:3000'
    restart: unless-stopped
    networks:
      - shared_app_net

networks:
  shared_app_net:
    external: true
    name: shared-db-network
