# 生产环境镜像
FROM node:22 AS production-stage

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

WORKDIR /app

# 这个 .output 目录将由 GitHub Actions 传输过来
COPY .output ./.output

EXPOSE 3000

# 为了能找到 node，直接使用绝对路径或确保在 PATH 中
CMD ["node", ".output/server/index.mjs"]