packages: []

catalogs:
  backend:
    '@types/pg': ^8.15.4
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.3
    pg: ^8.16.3
  build:
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.7.1
    '@nuxt/kit': ^4.0.1
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.3.3
    '@unocss/nuxt': ^66.3.3
    '@vueuse/nuxt': ^13.5.0
    nuxt: ^4.0.1
    unocss: ^66.3.3
    unplugin: ^2.3.5
    vite: ^7.0.6
  dev:
    '@antfu/eslint-config': ^4.19.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^3.0.3
  frontend:
    '@vueuse/core': ^13.5.0
    maplibre-gl: ^5.6.1
    pinia: ^3.0.3
    vue: ^3.5.18
  icons:
    '@iconify-json/carbon': ^1.2.11
    '@iconify-json/twemoji': ^1.2.2
  utils:
    '@types/zxcvbn': ^4.4.5
    bignumber.js: ^9.3.1
    csv-parse: ^6.1.0
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.39.7
    paseto-ts: ^2.0.5
    zod: ^4.0.8
    zxcvbn: ^4.4.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
