packages: []

catalogs:
  backend:
    '@types/pg': ^8.15.5
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.5
    pg: ^8.16.3
  build:
    '@nuxt/devtools': ^2.6.3
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.0.3
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.4.2
    '@unocss/nuxt': ^66.4.2
    '@vueuse/nuxt': ^13.7.0
    nuxt: ^4.0.3
    unocss: ^66.4.2
    unplugin: ^2.3.8
    vite: ^7.1.3
  dev:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.9.2
    vue-tsc: ^3.0.6
  frontend:
    '@floating-ui/vue': ^1.1.9
    '@vueuse/core': ^13.7.0
    maplibre-gl: ^5.7.0
    pinia: ^3.0.3
    vue: ^3.5.20
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/gis': ^1.2.5
    '@iconify-json/twemoji': ^1.2.4
  utils:
    '@types/zxcvbn': ^4.4.5
    bignumber.js: ^9.3.1
    csv-parse: ^6.1.0
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.39.10
    paseto-ts: ^2.0.5
    zod: ^4.1.3
    zxcvbn: ^4.4.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
