packages: []
catalogs:
  build:
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.7.0
    '@nuxt/kit': ^4.0.1
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.3.3
    '@unocss/nuxt': ^66.3.3
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.5.0
    nuxt: ^4.0.1
    unocss: ^66.3.3
    unplugin: ^2.3.5
    vite: ^7.0.5
  dev:
    '@antfu/eslint-config': ^4.18.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^3.0.3
  frontend:
    '@vueuse/core': ^13.5.0
    pinia: ^3.0.3
    vue: ^3.5.18
  icons:
    '@iconify-json/carbon': ^1.2.11
    '@iconify-json/twemoji': ^1.2.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
