name: Deploy via Git Pull

on:
  push:
    branches:
      - release # 当 release 分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 107.191.41.14
          username: root
          key: ${{ secrets.KEY }}
          script: |
            # [核心部署脚本]
            # 1. 进入项目目录
            cd /root/code/geo-history-studio

            # 2. 从 release 分支拉取最新的代码
            echo "Pulling latest code from release branch..."
            git pull origin release

            # 3. 使用 Docker Compose 重新构建并启动服务
            #    --build: 强制重新构建镜像，即使没有基础镜像的变化
            #    -d: 在后台运行
            #    --no-deps: 不重新启动依赖（postgres, redis）
            echo "Rebuilding and restarting services..."
            docker compose up -d --build --no-deps app

            # 4. (可选) 清理旧的、未使用的 Docker 镜像，释放空间
            echo "Pruning old Docker images..."
            docker image prune -f
            
            echo "Deployment finished successfully!"